# Generated by Django 4.2.10 on 2024-02-22 18:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identificationCode', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a]*$', message='تنها اعداد پذیرفته میشوند')], verbose_name='شماره ملی')),
                ('mobile', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a]*$', message='تنها اعداد پذیرفته میشوند')], verbose_name='شماره همراه')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('phone', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a]*$', message='تنها اعداد پذیرفته میشوند')], verbose_name='شماره تماس')),
                ('address', models.CharField(blank=True, max_length=4096, null=True, verbose_name='')),
                ('profile_pic', models.ImageField(default='pic1.jpg', upload_to='user/')),
                ('is_active', models.BooleanField(default=False, verbose_name='وضعیت فعالیت')),
                ('is_staff', models.BooleanField(default=False, verbose_name='دسترسی ادمین')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر')),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'مدیر'), (2, 'سرپرست فروش'), (3, 'پشتیبانی'), (4, 'مشاور'), (5, 'حسابدار'), (6, 'پخش کننده نماینده پزشکی'), (7, 'پخش کننده')], default=7)),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ عضویت')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='نام خانوادگی')),
                ('pic', models.ImageField(upload_to='profile/')),
                ('role', models.PositiveSmallIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=6, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_otp', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
