# Generated by Django 4.2.10 on 2024-02-23 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_profile_profile_pic_alter_profile_pic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='identificationCode',
            new_name='nid',
        ),
    ]
