# Generated by Django 4.2.10 on 2024-02-22 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=144, primary_key=True, serialize=False, unique=True, verbose_name='')),
                ('img', models.ImageField(upload_to='product/', verbose_name='')),
                ('slug', models.SlugField(allow_unicode=True, verbose_name='')),
                ('price', models.FloatField(verbose_name='')),
                ('description', models.CharField(max_length=400, verbose_name='')),
                ('capacity', models.PositiveBigIntegerField(verbose_name='')),
                ('prod_type', models.PositiveSmallIntegerField(choices=[('محصولات', 1), ('خدمات', 2)], default=1, verbose_name='')),
                ('is_verified', models.BooleanField(default=False, verbose_name='')),
                ('is_existed', models.BooleanField(default=True, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Instance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='product/')),
                ('slug', models.SlugField(allow_unicode=True)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=400)),
                ('capacity', models.PositiveBigIntegerField()),
                ('prod_type', models.PositiveSmallIntegerField(choices=[('محصولات', 1), ('خدمات', 2)], default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaser', models.CharField(max_length=50, verbose_name='')),
                ('price', models.FloatField(verbose_name='')),
                ('description', models.CharField(max_length=500, verbose_name='')),
                ('discount', models.FloatField(verbose_name='')),
                ('with_check', models.BooleanField(default=False, verbose_name='')),
                ('check_dealine', models.DateField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product', verbose_name='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
        ),
    ]
