# Generated by Django 4.2.10 on 2024-02-22 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField(blank=True, null=True)),
                ('end_at', models.DateField(blank=True, null=True)),
                ('sale_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saleManager', to=settings.AUTH_USER_MODEL)),
                ('tasks', models.ManyToManyField(to='product.product')),
                ('user', models.ManyToManyField(related_name='visitor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VisitorTaskDone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_done', models.BooleanField()),
                ('compeleted_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='duty.visitortask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
